
g_colors <- list(
  white = "#FFFFFF",
  blue = "#002856",
  sky = "#009AD7",
  tangerine = "#FF540A",
  lemon = "#FEC10D",
  rose = "#E81159",
  surf = "#06C4B0",
  steel = "#6F7878",
  black = "#000000",
  steel_accessible = "#535A5A",
  rose_accessible = "AF0D43"
)


cap_descriptions <- tribble(
  ~cap, ~short_description,
  "custinfo.1", "customer's name",
  "custinfo.2", "customer's contact info",
  "custinfo.3", "where customer is located",
  "custinfo.4", "if contact has special priveleges",
  "custinfo.5", "if contact is retention risk",
  "custinfo.6", "how customer feels",
  "prodinfo.1", "what customer has purchased",
  "prodinfo.2", "product renewal date",
  "prodinfo.3", "key aspects of customer's product",
  "prodinfo.4", "position product against competition",
  "external.1", "external info",
  "external.2", "connect with external partners",
  "external.3", "competitor's offers",
  "seamless.1", "customer's wait time",
  "seamless.2", "steps already taken",
  "seamless.3", "co-browsing",
  "decburden.1", "predict why customer contacted",
  "decburden.2", "evidence for predicted contact reason",
  "decburden.3", "customized issue resolution process",
  "decburden.4", "standard issue resolution process",
  "decburden.5", "NBA",
  "decburden.6", "NBO",
  "decburden.7", "NBC",
  "decburden.8", "NIA",
  "decburden.9", "suggests ways to use product better",
  "performance.1", "performance metrics",
  "performance.2", "how many customer are waiting",
  "performance.3", "script I must use",
  "performance.4", "phrases I can use",
  "performance.5", "performance advice",
  "performance.6", "help can listen and provide advice",
  "performance.7", "help can remote in",
  "performance.8", "collaborate",
  "lowvalue.1", "auto-disposition",
  "lowvalue.2", "summary",
  "lowvalue.3", "call notes",
  "lowvalue.4", "auto-update info across other systems",
  "lowvalue.5", "earlier customer journey info",
  "lowvalue.6", "auto-update transcation across other systems",
  "lowvalue.7", "authentication",
  "custhist.1", "prior team interactions",
  "custhist.2", "prior dept. interactions",
  "custhist.3", "how long customer has been a customer",
  "custhist.4", "if frequent/chronic contact",
  "sysdesign.1", "reduce info I have to remember",
  "sysdesign.2", "majority of info on one screen",
  "sysdesign.3", "single system",
  "sysdesign.4", "push relevant info",
  "sysdesign.5", "unnecessary info",
  "sysdesign.6", "info nearly categorized",
  "sysdesign.7", "info logically organized"
)
